Resources:
  myDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "music"
      AttributeDefinitions:
        -
          AttributeName: "PrimaryKey"
          AttributeType: "S"
        -
          AttributeName: "SortKey"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "PrimaryKey"
          KeyType: "HASH"
        -
          AttributeName: "SortKey"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5